# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=9.1' UI=true
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=8.4'
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=9.1' UI=true
  - DESTINATION='platform=iOS Simulator,name=iPad Air,OS=8.4'

script:
- set -o pipefail
- xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty
- if [ $UI ]; then xcodebuild -destination "$DESTINATION" -workspace Example/XCTest-Gherkin.xcworkspace -scheme XCTest-Gherkin-Example-UI -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty; fi
- pod lib lint
